# Generated by .github/workflows/update.yml -- do not edit by hand.
class Berth < Formula
  desc "Fast, daemonless local workspaces for parallel coding agents"
  homepage "https://github.com/Mrjwj34/berth"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
        url "https://github.com/Mrjwj34/berth/releases/download/v0.4.0/berth_0.4.0_darwin_arm64.tar.gz"
        sha256 "dd7cd28bcc46d2660ef7706ed8c719391f5126438e6f640195934f97e7009a46"
      else
        url "https://github.com/Mrjwj34/berth/releases/download/v0.4.0/berth_0.4.0_darwin_amd64.tar.gz"
        sha256 "c917c1979f1d00349ead4de436742ed66b5be506ec214f7e98c53ee9dbab9b95"
      end
  end

  on_linux do
    if Hardware::CPU.arm?
        url "https://github.com/Mrjwj34/berth/releases/download/v0.4.0/berth_0.4.0_linux_arm64.tar.gz"
        sha256 "4032e4f7cd50185d0c692f733fa862e9f7e64ecec56abd4b00035d5c1652ce67"
      else
        url "https://github.com/Mrjwj34/berth/releases/download/v0.4.0/berth_0.4.0_linux_amd64.tar.gz"
        sha256 "09728d50e2eda7f23ec5ed31b613aef448204ec82c13738c0032d4b78a5f83b0"
      end
  end

  livecheck do
    url "https://github.com/Mrjwj34/berth"
    strategy :github_latest
  end

  def install
    bin.install "berth"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/berth version")
  end
end
