# Generated by distribution/render.py -- do not edit by hand.
class Berth < Formula
  desc "Fast, daemonless local workspaces for parallel coding agents"
  homepage "https://github.com/Mrjwj34/berth"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Mrjwj34/berth/releases/download/v0.3.0/berth_0.3.0_darwin_arm64.tar.gz"
      sha256 "b332e6e7d1cbffac5ee086c62543ab1b737b9d34c69c0418d58ff9d18e56b424"
    else
      url "https://github.com/Mrjwj34/berth/releases/download/v0.3.0/berth_0.3.0_darwin_amd64.tar.gz"
      sha256 "1190abff29a4b39189fd1f8938d8554406748c728a2db82120ee16e14baa7a62"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Mrjwj34/berth/releases/download/v0.3.0/berth_0.3.0_linux_arm64.tar.gz"
      sha256 "a9dcbdff206c8b871cf950b8dffd1a5e91bbfaac6d9551f624c73938feda4686"
    else
      url "https://github.com/Mrjwj34/berth/releases/download/v0.3.0/berth_0.3.0_linux_amd64.tar.gz"
      sha256 "3d4888f493cf2bb8755302bb7118e0b07c2be53390756ca7608d5c6ab5ac2f7a"
    end
  end

  livecheck do
    url "https://github.com/Mrjwj34/berth"
    strategy :github_latest
  end

  def install
    bin.install "berth"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/berth version")
  end
end
